defaults: &defaults
  host: http://revanthreddy.koding.io
  port: 3000
  game_path: /games
  #host: localhost
  #port: 8000
  #game_path: /games

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults